import type { Metadata } from 'next';
import './globals.css';
import React, { ReactNode } from 'react';
import { headers } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  const currentUrl = headers().get('next-url') || '';
  console.log(currentUrl + ' |||');
  if (currentUrl === '/' || currentUrl === '') {
    return (
      <html>
        <body>{children}</body>
      </html>
    );
  } else {
    return (
      <html>
        <body>
          <div>
            <ul>
              <li>dma</li>
              <li>dma</li>
              <li>dma</li>
              <li>dma</li>
              <li>dma</li>
            </ul>
          </div>
          {children}
        </body>
      </html>
    );
  }
}
